/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.reforestworld;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import javax.swing.text.DefaultFormatterFactory;

/**
 *
 * @author Guilherme Quiller
 */
public class CadastroTela1 extends javax.swing.JFrame {

    /**
     * Creates new form CadastroTela
     */
    public CadastroTela1() {
        initComponents();
        nomeTextField1.setBackground(new java.awt.Color(0,0,0,1));
        emailTextField1.setBackground(new java.awt.Color(0,0,0,1));
        cpfTextField.setBackground(new java.awt.Color(0,0,0,1));
        SenhaPasswordField.setBackground(new java.awt.Color(0,0,0,1));
        ConfirmaSenhaPasswordField1.setBackground(new java.awt.Color(0,0,0,1));
        dataNascimentoTextField.setBackground(new java.awt.Color(0,0,0,1));
       
        
        jaTenhoContaButton.setOpaque(false);
        jaTenhoContaButton.setContentAreaFilled(false);
        jaTenhoContaButton.setForeground(Color.WHITE);
        
        cadastrarButton.setOpaque(false);
        cadastrarButton.setContentAreaFilled(false);
        cadastrarButton.setForeground(Color.WHITE);
        
        jLabel1.setFocusable(true);
        
        // Configuração do editor de texto da senha
        SenhaPasswordField.setEchoChar((char) 0);
        SenhaPasswordField.setForeground(Color.WHITE);
        SenhaPasswordField.setText("Senha");
        
        // Configuração do editor de texto da confirmação da senha
        ConfirmaSenhaPasswordField1.setEchoChar((char) 0);
        ConfirmaSenhaPasswordField1.setForeground(Color.WHITE);
        ConfirmaSenhaPasswordField1.setText("Confirme a Senha");
        
        
        
        
        
        cpfTextField.addKeyListener(new java.awt.event.KeyAdapter() {
    public void keyReleased(java.awt.event.KeyEvent evt) {
        cpfTextFieldKeyReleased(evt);
    }
    });
        
       

        
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        categoriacontaComboBox = new javax.swing.JComboBox<>();
        cpfTextField = new javax.swing.JTextField();
        SenhaPasswordField = new javax.swing.JPasswordField();
        dataNascimentoTextField = new javax.swing.JTextField();
        nomeTextField1 = new javax.swing.JTextField();
        emailTextField1 = new javax.swing.JTextField();
        tipocontaComboBox = new javax.swing.JComboBox<>();
        ConfirmaSenhaPasswordField1 = new javax.swing.JPasswordField();
        jaTenhoContaButton = new javax.swing.JButton();
        cadastrarButton = new javax.swing.JButton();
        sexoComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        categoriacontaComboBox.setBackground(new java.awt.Color(255, 255, 255));
        categoriacontaComboBox.setForeground(new java.awt.Color(0, 0, 0));
        categoriacontaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo da conta:", "Doador", "Agricultor", "Ambos" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Cadastro - Reforest World");
        getContentPane().setLayout(null);

        cpfTextField.setForeground(new java.awt.Color(255, 255, 255));
        cpfTextField.setText("CPF");
        cpfTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        cpfTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cpfTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cpfTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cpfTextFieldFocusLost(evt);
            }
        });
        cpfTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfTextFieldActionPerformed(evt);
            }
        });
        cpfTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cpfTextFieldKeyReleased(evt);
            }
        });
        getContentPane().add(cpfTextField);
        cpfTextField.setBounds(160, 280, 240, 30);

        SenhaPasswordField.setForeground(new java.awt.Color(255, 255, 255));
        SenhaPasswordField.setText("Senha");
        SenhaPasswordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        SenhaPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SenhaPasswordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SenhaPasswordFieldFocusLost(evt);
            }
        });
        SenhaPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SenhaPasswordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(SenhaPasswordField);
        SenhaPasswordField.setBounds(500, 120, 240, 30);

        dataNascimentoTextField.setForeground(new java.awt.Color(255, 255, 255));
        dataNascimentoTextField.setText("Data de Nascimento");
        dataNascimentoTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        dataNascimentoTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        dataNascimentoTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dataNascimentoTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dataNascimentoTextFieldFocusLost(evt);
            }
        });
        dataNascimentoTextField.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
                dataNascimentoTextFieldAncestorMoved(evt);
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
            }
        });
        dataNascimentoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataNascimentoTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(dataNascimentoTextField);
        dataNascimentoTextField.setBounds(500, 280, 240, 30);

        nomeTextField1.setForeground(new java.awt.Color(255, 255, 255));
        nomeTextField1.setText("Nome");
        nomeTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        nomeTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nomeTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nomeTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomeTextField1FocusLost(evt);
            }
        });
        nomeTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(nomeTextField1);
        nomeTextField1.setBounds(160, 120, 240, 30);

        emailTextField1.setForeground(new java.awt.Color(255, 255, 255));
        emailTextField1.setText("E-mail");
        emailTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        emailTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        emailTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailTextField1FocusLost(evt);
            }
        });
        emailTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(emailTextField1);
        emailTextField1.setBounds(160, 200, 240, 30);

        tipocontaComboBox.setBackground(new java.awt.Color(255, 255, 255));
        tipocontaComboBox.setForeground(new java.awt.Color(0, 0, 0));
        tipocontaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo da conta:", "Doador", "Agricultor", "Ambos" }));
        tipocontaComboBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));
        tipocontaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipocontaComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(tipocontaComboBox);
        tipocontaComboBox.setBounds(160, 360, 140, 30);

        ConfirmaSenhaPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        ConfirmaSenhaPasswordField1.setText("Confirme a Senha");
        ConfirmaSenhaPasswordField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        ConfirmaSenhaPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ConfirmaSenhaPasswordField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ConfirmaSenhaPasswordField1FocusLost(evt);
            }
        });
        ConfirmaSenhaPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmaSenhaPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(ConfirmaSenhaPasswordField1);
        ConfirmaSenhaPasswordField1.setBounds(500, 200, 240, 30);

        jaTenhoContaButton.setBackground(new java.awt.Color(255, 255, 255));
        jaTenhoContaButton.setForeground(new java.awt.Color(0, 0, 0));
        jaTenhoContaButton.setText("Já Tenho Conta");
        jaTenhoContaButton.setToolTipText("");
        jaTenhoContaButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jaTenhoContaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jaTenhoContaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaTenhoContaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jaTenhoContaButton);
        jaTenhoContaButton.setBounds(30, 20, 150, 40);

        cadastrarButton.setBackground(new java.awt.Color(255, 255, 255));
        cadastrarButton.setForeground(new java.awt.Color(0, 0, 0));
        cadastrarButton.setText("Cadastrar-se");
        cadastrarButton.setToolTipText("");
        cadastrarButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        cadastrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrarButton);
        cadastrarButton.setBounds(500, 430, 240, 40);

        sexoComboBox.setBackground(new java.awt.Color(255, 255, 255));
        sexoComboBox.setForeground(new java.awt.Color(0, 0, 0));
        sexoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "sexo:", "Masculino", "Feminino", "Prefiro não informar" }));
        sexoComboBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));
        getContentPane().add(sexoComboBox);
        sexoComboBox.setBounds(500, 360, 139, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ImagemCadastro.png"))); // NOI18N
        jLabel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel1FocusGained(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, -10, 920, 580);

        setSize(new java.awt.Dimension(926, 571));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void cpfTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpfTextFieldFocusGained
    String login = cpfTextField.getText();
           if (login.equals("CPF")) {
               cpfTextField.setText("");
           }
    }//GEN-LAST:event_cpfTextFieldFocusGained

    private void cpfTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpfTextFieldFocusLost
        String login = cpfTextField.getText();
        if (login.equals("CPF")) {
            cpfTextField.setText("");
        }
    }//GEN-LAST:event_cpfTextFieldFocusLost

    private void cpfTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfTextFieldActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfTextFieldActionPerformed

    private void nomeTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeTextField1FocusGained
String login = nomeTextField1.getText();
        if (login.equals("Nome")) {
            nomeTextField1.setText("");
        }
    }//GEN-LAST:event_nomeTextField1FocusGained

    private void nomeTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeTextField1FocusLost
String login = nomeTextField1.getText();
        if (login.equals("")) {
            nomeTextField1.setText("Nome");
        }
    }//GEN-LAST:event_nomeTextField1FocusLost

    private void nomeTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTextField1ActionPerformed

    private void emailTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTextField1FocusGained
String login = emailTextField1.getText();
        if (login.equals("E-mail")) {
            emailTextField1.setText("");
        }       // TODO add your handling code here:
    }//GEN-LAST:event_emailTextField1FocusGained

    private void emailTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTextField1FocusLost
String login = emailTextField1.getText();
        if (login.equals("")) {
            emailTextField1.setText("E-mail");
        }
    }//GEN-LAST:event_emailTextField1FocusLost

    private void emailTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextField1ActionPerformed

    private void jLabel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1FocusGained

    private void SenhaPasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SenhaPasswordFieldFocusGained
     String login = SenhaPasswordField.getText();
        if (login.equals("Senha")) {
            SenhaPasswordField.setText("");
        }
        
        
            SenhaPasswordField.setEchoChar('*'); 
            SenhaPasswordField.setForeground(Color.WHITE); 
           
        
    }//GEN-LAST:event_SenhaPasswordFieldFocusGained

    private void SenhaPasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SenhaPasswordFieldFocusLost
    String login = SenhaPasswordField.getText();
        if (login.equals("")) {
            SenhaPasswordField.setText("Senha");
            SenhaPasswordField.setEchoChar((char) 0); // Remove o caractere de visualização de senha
        }
        
         
        
            
        
    }//GEN-LAST:event_SenhaPasswordFieldFocusLost

    private void SenhaPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenhaPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SenhaPasswordFieldActionPerformed

    private void ConfirmaSenhaPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ConfirmaSenhaPasswordField1FocusGained
String login = ConfirmaSenhaPasswordField1.getText();
        if (login.equals("Confirme a Senha")) {
            ConfirmaSenhaPasswordField1.setText("");
        }    
        
        
            ConfirmaSenhaPasswordField1.setEchoChar('*'); 
            ConfirmaSenhaPasswordField1.setForeground(Color.WHITE);
    }//GEN-LAST:event_ConfirmaSenhaPasswordField1FocusGained

    private void ConfirmaSenhaPasswordField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ConfirmaSenhaPasswordField1FocusLost
String login = ConfirmaSenhaPasswordField1.getText();
        if (login.equals("")) {
            ConfirmaSenhaPasswordField1.setText("Confirme a Senha");
            ConfirmaSenhaPasswordField1.setEchoChar((char) 0); // Remove o caractere de visualização de senha
        }        
         
        
           
    }//GEN-LAST:event_ConfirmaSenhaPasswordField1FocusLost

    private void ConfirmaSenhaPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmaSenhaPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmaSenhaPasswordField1ActionPerformed

    private void tipocontaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipocontaComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipocontaComboBoxActionPerformed

    private void dataNascimentoTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataNascimentoTextFieldFocusGained
String login = dataNascimentoTextField.getText();
        if (login.equals("Data de Nascimento")) {
            dataNascimentoTextField.setText("");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_dataNascimentoTextFieldFocusGained

    private void dataNascimentoTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataNascimentoTextFieldFocusLost
String login = dataNascimentoTextField.getText();
        if (login.equals("")) {
            dataNascimentoTextField.setText("Data de Nascimento");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_dataNascimentoTextFieldFocusLost

    private void dataNascimentoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataNascimentoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataNascimentoTextFieldActionPerformed

    private void cadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarButtonActionPerformed
        JOptionPane.showMessageDialog(null, "Cadastro criado com Sucesso.");
        
    LoginTela loginTela = new LoginTela(); 
    loginTela.setVisible(true);
    dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarButtonActionPerformed

    private void dataNascimentoTextFieldAncestorMoved(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_dataNascimentoTextFieldAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_dataNascimentoTextFieldAncestorMoved

    private void jaTenhoContaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaTenhoContaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jaTenhoContaButtonActionPerformed

    private void cpfTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cpfTextFieldKeyReleased
     String text = cpfTextField.getText().replaceAll("[^\\d]", ""); // Remove caracteres não numéricos

    // Verifica se o CPF possui 11 dígitos
    if (text.length() == 11) {
        // Formata o CPF
        String cpfFormatado = String.format("%s.%s.%s-%s", text.substring(0, 3), text.substring(3, 6), text.substring(6, 9), text.substring(9));
        
        // Define o texto formatado no campo CPF
        cpfTextField.setText(cpfFormatado);
        
        if (cpfTextField.getText().length() > 15) {
            cpfTextField.setText(cpfTextField.getText().substring(0, 15));
        }
        
        String CPF = cpfTextField.getText();
        CPF = CPF.replaceAll("[^0-9]", "");
        JOptionPane.showConfirmDialog(null, CPF);
        
        
        
    }
    
    }//GEN-LAST:event_cpfTextFieldKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroTela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroTela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroTela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroTela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroTela1().setVisible(true);
            }
         
        });
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ConfirmaSenhaPasswordField1;
    private javax.swing.JPasswordField SenhaPasswordField;
    private javax.swing.JButton cadastrarButton;
    private javax.swing.JComboBox<String> categoriacontaComboBox;
    private javax.swing.JTextField cpfTextField;
    private javax.swing.JTextField dataNascimentoTextField;
    private javax.swing.JTextField emailTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jaTenhoContaButton;
    private javax.swing.JTextField nomeTextField1;
    private javax.swing.JComboBox<String> sexoComboBox;
    private javax.swing.JComboBox<String> tipocontaComboBox;
    // End of variables declaration//GEN-END:variables
}
