/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.reforestworld;

/**
 *
 * @author Guilherme Quiller
 */
public class CadastroTela2 extends javax.swing.JFrame {

    /**
     * Creates new form CadastroTela
     */
    public CadastroTela2() {
        initComponents();
        SenhaPasswordField.setBackground(new java.awt.Color(0,0,0,1));
        ConfirmaSenhaPasswordField1.setBackground(new java.awt.Color(0,0,0,1));
        jLabel1.setFocusable(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ConfirmaSenhaPasswordField1 = new javax.swing.JPasswordField();
        SenhaPasswordField = new javax.swing.JPasswordField();
        CadastrarButton = new javax.swing.JButton();
        jaTenhoContaButton = new javax.swing.JButton();
        categoriacontaComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Cadastro - Reforest World");
        getContentPane().setLayout(null);

        ConfirmaSenhaPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        ConfirmaSenhaPasswordField1.setText("Confirme a Senha");
        ConfirmaSenhaPasswordField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        ConfirmaSenhaPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ConfirmaSenhaPasswordField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ConfirmaSenhaPasswordField1FocusLost(evt);
            }
        });
        ConfirmaSenhaPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmaSenhaPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(ConfirmaSenhaPasswordField1);
        ConfirmaSenhaPasswordField1.setBounds(30, 200, 240, 30);

        SenhaPasswordField.setForeground(new java.awt.Color(255, 255, 255));
        SenhaPasswordField.setText("Senha");
        SenhaPasswordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        SenhaPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SenhaPasswordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SenhaPasswordFieldFocusLost(evt);
            }
        });
        SenhaPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SenhaPasswordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(SenhaPasswordField);
        SenhaPasswordField.setBounds(30, 140, 240, 30);

        CadastrarButton.setBackground(new java.awt.Color(255, 255, 255));
        CadastrarButton.setForeground(new java.awt.Color(0, 0, 0));
        CadastrarButton.setText("Cadastrar-se");
        CadastrarButton.setToolTipText("");
        CadastrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CadastrarButton);
        CadastrarButton.setBounds(320, 200, 140, 30);

        jaTenhoContaButton.setBackground(new java.awt.Color(255, 255, 255));
        jaTenhoContaButton.setForeground(new java.awt.Color(0, 0, 0));
        jaTenhoContaButton.setText("Já Tenho Conta");
        jaTenhoContaButton.setToolTipText("");
        jaTenhoContaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaTenhoContaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jaTenhoContaButton);
        jaTenhoContaButton.setBounds(20, 10, 140, 40);

        categoriacontaComboBox.setBackground(new java.awt.Color(255, 255, 255));
        categoriacontaComboBox.setForeground(new java.awt.Color(0, 0, 0));
        categoriacontaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo da conta:", "Doador", "Agricultor", "Ambos" }));
        getContentPane().add(categoriacontaComboBox);
        categoriacontaComboBox.setBounds(320, 140, 140, 26);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ImagemCadastro.jpg"))); // NOI18N
        jLabel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel1FocusGained(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 643, 395);

        setSize(new java.awt.Dimension(659, 427));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1FocusGained

    private void jaTenhoContaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaTenhoContaButtonActionPerformed
LoginTela loginTela = new LoginTela(); 
    loginTela.setVisible(true);
    dispose();        
    }//GEN-LAST:event_jaTenhoContaButtonActionPerformed

    private void CadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarButtonActionPerformed
    LoginTela loginTela = new LoginTela(); 
    loginTela.setVisible(true);
    dispose();      // TODO add your handling code here:
    }//GEN-LAST:event_CadastrarButtonActionPerformed

    private void SenhaPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenhaPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SenhaPasswordFieldActionPerformed

    private void SenhaPasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SenhaPasswordFieldFocusGained
     SenhaPasswordField.setText("");    // TODO add your handling code here:
    }//GEN-LAST:event_SenhaPasswordFieldFocusGained

    private void SenhaPasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SenhaPasswordFieldFocusLost
    SenhaPasswordField.setText("Senha");          // TODO add your handling code here:
    }//GEN-LAST:event_SenhaPasswordFieldFocusLost

    private void ConfirmaSenhaPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ConfirmaSenhaPasswordField1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmaSenhaPasswordField1FocusGained

    private void ConfirmaSenhaPasswordField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ConfirmaSenhaPasswordField1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmaSenhaPasswordField1FocusLost

    private void ConfirmaSenhaPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmaSenhaPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmaSenhaPasswordField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroTela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroTela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroTela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroTela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroTela2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastrarButton;
    private javax.swing.JPasswordField ConfirmaSenhaPasswordField1;
    private javax.swing.JPasswordField SenhaPasswordField;
    private javax.swing.JComboBox<String> categoriacontaComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jaTenhoContaButton;
    // End of variables declaration//GEN-END:variables
}
