/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.reforestworld;

/**
 *
 * @author Guilherme Quiller
 */
public class CadastroTela1 extends javax.swing.JFrame {

    /**
     * Creates new form CadastroTela
     */
    public CadastroTela1() {
        initComponents();
        nomeTextField1.setBackground(new java.awt.Color(0,0,0,1));
        emailTextField1.setBackground(new java.awt.Color(0,0,0,1));
        cpfTextField.setBackground(new java.awt.Color(0,0,0,1));
        jLabel1.setFocusable(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cpfTextField = new javax.swing.JTextField();
        nomeTextField1 = new javax.swing.JTextField();
        emailTextField1 = new javax.swing.JTextField();
        proximoButton = new javax.swing.JButton();
        jaTenhoContaButton = new javax.swing.JButton();
        idadeComboBox = new javax.swing.JComboBox<>();
        sexoComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Cadastro - Reforest World");
        getContentPane().setLayout(null);

        cpfTextField.setForeground(new java.awt.Color(255, 255, 255));
        cpfTextField.setText("CPF");
        cpfTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        cpfTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cpfTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cpfTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cpfTextFieldFocusLost(evt);
            }
        });
        cpfTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(cpfTextField);
        cpfTextField.setBounds(30, 260, 240, 30);

        nomeTextField1.setForeground(new java.awt.Color(255, 255, 255));
        nomeTextField1.setText("Nome");
        nomeTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        nomeTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nomeTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nomeTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomeTextField1FocusLost(evt);
            }
        });
        nomeTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(nomeTextField1);
        nomeTextField1.setBounds(30, 140, 240, 30);

        emailTextField1.setForeground(new java.awt.Color(255, 255, 255));
        emailTextField1.setText("E-mail");
        emailTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        emailTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        emailTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailTextField1FocusLost(evt);
            }
        });
        emailTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(emailTextField1);
        emailTextField1.setBounds(30, 200, 240, 30);

        proximoButton.setBackground(new java.awt.Color(255, 255, 255));
        proximoButton.setForeground(new java.awt.Color(0, 0, 0));
        proximoButton.setText("Proximo");
        proximoButton.setToolTipText("");
        proximoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(proximoButton);
        proximoButton.setBounds(330, 260, 140, 30);

        jaTenhoContaButton.setBackground(new java.awt.Color(255, 255, 255));
        jaTenhoContaButton.setForeground(new java.awt.Color(0, 0, 0));
        jaTenhoContaButton.setText("Já Tenho Conta");
        jaTenhoContaButton.setToolTipText("");
        jaTenhoContaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaTenhoContaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jaTenhoContaButton);
        jaTenhoContaButton.setBounds(20, 10, 140, 40);

        idadeComboBox.setBackground(new java.awt.Color(255, 255, 255));
        idadeComboBox.setForeground(new java.awt.Color(0, 0, 0));
        idadeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "idade", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80+" }));
        idadeComboBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));
        getContentPane().add(idadeComboBox);
        idadeComboBox.setBounds(330, 200, 140, 30);

        sexoComboBox.setBackground(new java.awt.Color(255, 255, 255));
        sexoComboBox.setForeground(new java.awt.Color(0, 0, 0));
        sexoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "sexo:", "Masculino", "Feminino", "Prefiro não informar" }));
        sexoComboBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));
        getContentPane().add(sexoComboBox);
        sexoComboBox.setBounds(330, 140, 139, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ImagemCadastro.jpg"))); // NOI18N
        jLabel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel1FocusGained(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 643, 395);

        setSize(new java.awt.Dimension(659, 427));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cpfTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpfTextFieldFocusGained
        cpfTextField.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfTextFieldFocusGained

    private void cpfTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpfTextFieldFocusLost
        cpfTextField.setText("Usuario");
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfTextFieldFocusLost

    private void cpfTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfTextFieldActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_cpfTextFieldActionPerformed

    private void nomeTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeTextField1FocusGained
nomeTextField1.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTextField1FocusGained

    private void nomeTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeTextField1FocusLost
nomeTextField1.setText("Nome");        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTextField1FocusLost

    private void nomeTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTextField1ActionPerformed

    private void emailTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTextField1FocusGained
emailTextField1.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextField1FocusGained

    private void emailTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTextField1FocusLost
emailTextField1.setText("E-mail");        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextField1FocusLost

    private void emailTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextField1ActionPerformed

    private void jLabel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1FocusGained

    private void jaTenhoContaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaTenhoContaButtonActionPerformed
LoginTela loginTela = new LoginTela(); 
    loginTela.setVisible(true);
    dispose();        
    }//GEN-LAST:event_jaTenhoContaButtonActionPerformed

    private void proximoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proximoButtonActionPerformed
    CadastroTela2 cadastrotela2 = new CadastroTela2(); 
    cadastrotela2.setVisible(true);
    dispose();     // TODO add your handling code here:
    }//GEN-LAST:event_proximoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroTela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroTela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroTela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroTela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroTela1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cpfTextField;
    private javax.swing.JTextField emailTextField1;
    private javax.swing.JComboBox<String> idadeComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jaTenhoContaButton;
    private javax.swing.JTextField nomeTextField1;
    private javax.swing.JButton proximoButton;
    private javax.swing.JComboBox<String> sexoComboBox;
    // End of variables declaration//GEN-END:variables
}
