/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package RW.forms;
 
import RW.Tabbed.TabbedForm;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;

/**
 *
 * @author Fernando
 */
public class SobreNosTela extends TabbedForm {

    /**
     * Creates new form CadastroEventosTela
     */
    public SobreNosTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Foto2 = new javax.swing.JLabel();
        Foto1 = new javax.swing.JLabel();
        NEXT = new javax.swing.JButton();
        PREV = new javax.swing.JButton();
        emailButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 768));
        jPanel1.setLayout(null);

        Foto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Layout Gabriel3.png"))); // NOI18N
        Foto2.setText("Foto2");
        jPanel1.add(Foto2);
        Foto2.setBounds(20, 260, 980, 220);

        Foto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Layout Raul3.png"))); // NOI18N
        Foto1.setText("Foto1");
        jPanel1.add(Foto1);
        Foto1.setBounds(20, 240, 980, 260);

        NEXT.setText("NEXT");
        jPanel1.add(NEXT);
        NEXT.setBounds(465, 163, 70, 50);

        PREV.setText("PREV");
        jPanel1.add(PREV);
        PREV.setBounds(460, 530, 70, 40);

        emailButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailButtonMouseClicked(evt);
            }
        });
        emailButton.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                emailButtonPropertyChange(evt);
            }
        });
        jPanel1.add(emailButton);
        emailButton.setBounds(410, 720, 240, 20);
        emailButton.getAccessibleContext().setAccessibleName("emailButton");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BackgroundTheForest.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1024, 766);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void emailButtonPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_emailButtonPropertyChange
            emailButton.setOpaque(false);
            emailButton.setContentAreaFilled(false);
            emailButton.setBorderPainted(false);
    }//GEN-LAST:event_emailButtonPropertyChange

    private void emailButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailButtonMouseClicked
     
                String email = "contato@reforestworld.com.br"; // Endereço de e-mail desejado
        try {
            URI uri = new URI("mailto:" + email);
            Desktop.getDesktop().mail(uri);
        } catch (IOException | URISyntaxException ex) {
        }
    }//GEN-LAST:event_emailButtonMouseClicked

   
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Foto1;
    private javax.swing.JLabel Foto2;
    private javax.swing.JButton NEXT;
    private javax.swing.JButton PREV;
    private javax.swing.JButton emailButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
